### ISSUE TITLE
BOUNTY: Convert the endpoints to a smart router like litellm does in python

### ISSUE THREAD

**Issue by sandys** [arakoodev/EdgeChains#286]
this bounty refers to the JS SDK only http://github.com/arakoodev/EdgeChains/tree/ts/JS/edgechains

we are super inspired by Litellm in python (and have a lot of respect for them) - https://github.com/BerriAI/litellm and we want to create a similar infrastructure in Edgechain.js using Typescript. We are hoping libraries like axios makes this easier.

the four features we want are these:
1. load balance between multiple deployments. It picks the deployment which is below rate-limit and has the least amount of tokens used. (only openai, google palm and cohere needed). this includes basic reliability features (https://docs.litellm.ai/docs/routing#basic-reliability) like timeouts/retries/etc. you can use `axios.interceptors.response.use` to achieve these.
2. streaming capability
3. token usage - https://docs.litellm.ai/docs/completion/token_usage 
4. logging - https://docs.litellm.ai/docs/observability/callbacks (only sentry and posthog needed)

Once created, you will replace the Endpoint class with this new infrastructure (https://github.com/arakoodev/EdgeChains/blob/ts/JS/edgechains/lib/src/lib/endpoints/OpenAiEndpoint.ts)

project will be deemed complete when:
1. you add testcases for all the features above.
2. mock the openai, palm and cohere endpoints for testing. (you can take inspiration from here https://github.com/polly3d/mockai)
3. you have deleted the current endpoint classes and replaced it with your new classes in all examples and testcases.

NOTE: the core of edgechains is the usage of jsonnet (https://jsonnet.org/) configuration to manage all kinds of config - like prompts, etc. we will prefer that as far as possible, we use jsonnet to configure this routing.

**Comment by rajdip-b** [comment]
/attempt #286

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clpnjwx3l0002ju0fs2ajop5w/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by rajdip-b** [comment]
@sandys can i be assigned this issue?

**Comment by sandys** [comment]
@rajdip-b happy to. 
but first want to check if you understand what has to be achieved ? any doubts, etc ?

**Comment by guhitb** [comment]
@rajdip-b Any interest in collaborating on this?

**Comment by rajdip-b** [comment]
@sandys As per my understanding, the main challenge is creating the load balancer in the endpoints of `OpenAiEndpoint.ts`. I was going through the references you mentioned and have a clarity over what needs to be implemented. I would have to do some further digging about the how's of the implementation, but yes, I feel I can definitely give it a shot!

And not to mention, as and when issues come up, I will ping you about them.

**Comment by sandys** [comment]
@rajdip-b there are 4 capabilities needed (as mentioned in my original post). it is important that you look at all four, because the architecture will need to be inclusive.
also, this architecture will REPLACE the current endpoint structure

**Comment by rajdip-b** [comment]
@guhitb, are you familiar with the project structure/implementation details? I would be happy to collaborate!

**Comment by rajdip-b** [comment]
> @rajdip-b there are 4 capabilities needed (as mentioned in my original post). it is important that you look at all four, because the architecture will need to be inclusive. also, this architecture will REPLACE the current endpoint structure

Yeah, of course, I understand that. For me, I feel the challenge would be implementing load balancing, hence mentioned that. As for the rest, I feel they can be done with lesser efforts than the former.

**Comment by sandys** [comment]
very well. assigned to @rajdip-b best wishes. please feel free to drop in to discord if u want to discuss anything quickly. https://discord.gg/Avsbume2

**Comment by rajdip-b** [comment]
> very well. assigned to @rajdip-b best wishes. please feel free to drop in to discord if u want to discuss anything quickly. https://discord.gg/Avsbume2

Discord is my go-to for discussion! Hopping in right now!

**Comment by guhitb** [comment]
@rajdip-b Not yet, aside from browsing through the repo today. I don't have much experience with open source, but I'm sure I can help with mocks, logging, tests, etc. The load balancing part feels a little daunting though.

**Comment by rajdip-b** [comment]
> @rajdip-b Not yet, aside from browsing through the repo today. I don't have much experience with open source, but I'm sure I can help with mocks, logging, tests, etc. The load balancing part feels a little daunting though.

Hey sure thing! We can pair up!

Drop me a text on discord! _the_heisenberg

**Comment by sandys** [comment]
Hi rajdip
We are not totally in favor of splitting the bounty right now. No offense,
but we are looking to reward the person who can complete the work with the
best architecture to benefit end users.

We realise that there is a spirit of collaboration at play - we request you
do this offline within yourself if you want.

We are requesting for this option since if yourSelf you cannot pull this
off...we would like to reserve the right to assign this to someone else
entirely.

At this time, we believe in YOUR abilities and we would like for the reward
to reflect that


Case in point - there was this massive crash and burn on algora with the
ziglang folks cos of this. And we would like to avoid a situation like
that. So mentioning up front !

**Comment by rajdip-b** [comment]
@sandys Ah, that's bad. Sure, I'll take this issue op alone. @guhitb You can still connect with me in case you want to collab on any other issue! Hope that's fine by everyone :D

**Comment by rajdip-b** [comment]
Hey @sandys, I have started with the docs today. I have went through the code base of litellm and how they implement their stuff. I also went though openai docs. I have some questions and suggestions that I would like to share and discuss with you. I couldn't find you in discord in you channel. mind pinging you handle in here? ill open a thread in discord and tag you in it!

**Comment by sandys** [comment]
just create a new thread in the "support" channel (and mention the bug
number). the right people will get back to you

**Comment by rajdip-b** [comment]
Created! @sandys

**Comment by Sajiyah-Salat** [comment]
Hello @rajdip-b are you still working on this. Let me know your discord handle. I would like to connect with you there

**Comment by rajdip-b** [comment]
Hey @Sajiyah-Salat, there has been a blocker, and hence I have paused my work currently.

**Comment by Sajiyah-Salat** [comment]
Okay. Thanks for the reply

**Comment by Sambit003** [comment]
@sandys  @Sajiyah-Salat can I work on this?

**Comment by rajdip-b** [comment]
@sandys I'm dropping my attempt on this issue. For anyone who attempts next, feel free to pick up from my PR.

**Comment by snigdha510** [comment]
can I work on this?

**Comment by sandys** [comment]
hi snigdha
thanks for your interest. can u please join discord and message please ? we
will be able to assign this (or other projects) if you are interested
https://discord.gg/cby9pQKT

**Comment by Sadaf-A** [comment]
Hey @sandys !
Is this up for contribution?

**Comment by PIYUSH-MISHRA-00** [comment]
/attempt #286

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clpnjwx3l0002ju0fs2ajop5w/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by evonloch** [comment]
@sandys Is this still open for contribution?

**Comment by Harshvardhan-91** [comment]
@sandys can i work on this?

**Comment by mudaly10-coder** [comment]
Auto-claim: I'm taking this on.
- Part of my automated bounty triage.
Payout~$0

**Comment by mudaly10-coder** [comment]
Automated claim test: acknowledging bounty.

**Comment by mudaly10-coder** [comment]
Automated claim test: acknowledging bounty.

**Comment by mudaly10-coder** [comment]
Automated claim test.

**Comment by akobir-1** [comment]
/attempt #286

Hi! I would like to work on this. I have extensive experience in Backend Engineering and AI systems.

My Implementation Plan: 1. Create a "SmartRouter" class that mimics LiteLLM's logic in TypeScript. 2. Implement Load Balancing strategies (Random / Least Used) using Axios interceptors. 3. Add failover/retry logic for OpenAI, Cohere, and Google PaLM endpoints. 4. Integrate Token Usage tracking and Logging (Sentry/Posthog). 5. Replace the existing OpenAiEndpoint class with the new architecture.

Starting the analysis now.

**Comment by matiasmagni** [comment]
/attempt #286

# Implementation Plan: LiteLLM-like Infrastructure for EdgeChains.js

## Issue: #286 - Create LiteLLM-like routing infrastructure

---

## Overview

This implementation creates a LiteLLM-inspired routing system for EdgeChains.js that provides:
1. Load balancing across multiple LLM deployments
2. Streaming support
3. Token usage tracking
4. Logging callbacks (Sentry + Posthog)

**Target Directory:** `JS/edgechains/arakoodev/src/ai/src/lib/router/`

---

## Phase 1: Module Structure

```
router/
├── index.ts                      # Main exports
├── Router.ts                      # Main router class
├── types.ts                      # TypeScript interfaces
├── providers/
│   ├── OpenAIProvider.ts        # OpenAI-compatible provider
│   ├── GeminiProvider.ts        # Google Palm/Gemini provider
│   └── CohereProvider.ts        # Cohere provider
├── strategies/
│   ├── SimpleShuffle.ts         # Random load balancing
│   ├── LeastTokens.ts           # Least tokens used (primary)
│   └── LatencyBased.ts          # Fastest response time
├── interceptors/
│   └── axiosInterceptors.ts     # Timeout/retry logic
├── logging/
│   ├── CallbackManager.ts       # Callback handler
│   ├── SentryLogger.ts          # Sentry integration
│   └── PosthogLogger.ts         # Posthog integration
└── utils/
    ├── tokenCounter.ts          # Token usage tracking
    └── costCalculator.ts        # Cost calculation
```

---

## Phase 2: Core Implementation

### 2.1 Types Definition (`types.ts`)

```typescript
interface DeploymentConfig {
  modelName: string;        // Logical model name (e.g., "gpt-3.5-turbo")
  provider: "openai" | "gemini" | "cohere";
  apiKey: string;
  apiBase?: string;         // Custom endpoint URL
  rpm?: number;             // Requests per minute limit
  tpm?: number;             // Tokens per minute limit
  priority?: number;        // Lower = higher priority
}

interface RouterConfig {
  modelList: DeploymentConfig[];
  routingStrategy: "simple-shuffle" | "least-tokens" | "latency-based";
  numRetries: number;
  timeout: number;           // Request timeout in ms
  cooldownTime?: number;    // Failed deployment cooldown
  allowedFails?: number;   // Failures before cooldown
}

interface TokenUsage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
  costUSD: number;
}

interface Deployment {
  config: DeploymentConfig;
  currentTokens: number;
  currentRequests: number;
  failures: number;
  cooldownUntil?: number;
  latency?: number;
}
```

### 2.2 Axios Interceptors (`interceptors/axiosInterceptors.ts`)

- Handle timeouts
- Handle 429 (rate limit) responses
- Implement exponential backoff retry
- Track failures for cooldown mechanism

### 2.3 Router Class (`Router.ts`)

**Key Methods:**
- `completion()` - Make completion request with routing
- `streamingCompletion()` - Streaming variant
- `_selectDeployment()` - Select best deployment based on strategy
- `_checkRateLimit()` - Verify deployment is within limits
- `_updateUsage()` - Update token/request counts after response
- `_handleFailure()` - Track failure and apply cooldown

**Load Balancing Logic:**
1. Filter deployments by provider
2. Exclude deployments in cooldown
3. Exclude deployments above rate limit (RPM/TPM)
4. Sort by strategy (least-tokens, latency, simple-shuffle)
5. Return best deployment

### 2.4 Providers

#### OpenAIProvider
- Uses `/v1/chat/completions` endpoint
- Supports standard OpenAI + Azure OpenAI
- Parses streaming and non-streaming responses

#### GeminiProvider
- Uses Google Generative Language API
- Maps to Gemini/Gemini-Pro models

#### CohereProvider
- Uses Cohere Generate endpoint
- Maps to Command models

### 2.5 Token Usage Tracking

- Extract `usage` field from API responses
- Calculate cost using model pricing tables
- Track cumulative usage per deployment
- Return token usage in response

### 2.6 Logging Callbacks

#### CallbackManager
```typescript
type CallbackEvent = "success" | "failure" | "pre-call" | "post-call";

interface LogPayload {
  model: string;
  deployment: string;
  tokens: TokenUsage;
  latency: number;
  status: "success" | "failure";
  error?: string;
  messages?: any[];
  response?: any;
}
```

#### SentryLogger
- Log errors via `Sentry.captureException()`
- Add breadcrumb for each LLM call

#### PosthogLogger
- Send `llm_call` events with token usage
- Include model, latency, cost metadata

---

## Phase 3: JSONNet Configuration

### routing.jsonnet

```jsonnet
local openai_api_key = std.extVar('OPENAI_API_KEY');
local gemini_api_key = std.extVar('GEMINI_API_KEY');
local cohere_api_key = std.extVar('COHERE_API_KEY');
local sentry_dsn = std.extVar('SENTRY_DSN');
local posthog_key = std.extVar('POSTHOG_API_KEY');

{
  router_settings: {
    routing_strategy: "least-tokens",
    num_retries: 3,
    timeout: 30000,
    cooldown_time: 60,
    allowed_fails: 3,
  },

  model_list: [
    {
      model_name: "gpt-3.5-turbo",
      provider: "openai",
      api_key: openai_api_key,
      api_base: "https://api.openai.com/v1",
      rpm: 3000,
      tpm: 90000,
      priority: 1,
    },
    {
      model_name: "gpt-3.5-turbo",
      provider: "openai",
      api_key: openai_api_key,
      api_base: "https://api.openai.com/v1",
      rpm: 3000,
      tpm: 90000,
      priority: 2,
    },
    {
      model_name: "gemini-pro",
      provider: "gemini",
      api_key: gemini_api_key,
      rpm: 60,
    },
    {
      model_name: "command-r",
      provider: "cohere",
      api_key: cohere_api_key,
      rpm: 100,
    },
  ],

  callbacks: {
    sentry: {
      enabled: true,
      dsn: sentry_dsn,
    },
    posthog: {
      enabled: true,
      api_key: posthog_key,
      api_host: "https://app.posthog.com",
    },
  },
}
```

### Usage in Code

```typescript
import { Router } from "@arakoodev/edgechains.js/ai";
import Jsonnet from "@arakoodev/jsonnet";

const jsonnet = new Jsonnet();
jsonnet.extString('OPENAI_API_KEY', process.env.OPENAI_API_KEY);
jsonnet.extString('GEMINI_API_KEY', process.env.GEMINI_API_KEY);
jsonnet.extString('COHERE_API_KEY', process.env.COHERE_API_KEY);
jsonnet.extString('SENTRY_DSN', process.env.SENTRY_DSN);
jsonnet.extString('POSTHOG_API_KEY', process.env.POSTHOG_API_KEY);

const config = JSON.parse(jsonnet.evaluateFile('./routing.jsonnet'));
const router = new Router(config);
```

---

## Phase 4: Tests

### Test Location
`JS/edgechains/arakoodev/src/ai/src/tests/router/`

### Mock Servers

#### mocks/OpenAIMockServer.ts
- Mock `/v1/chat/completions` endpoint
- Support streaming via SSE
- Simulate rate limits and errors

#### mocks/GeminiMockServer.ts
- Mock Google Generative Language API
- Return token usage in response

#### mocks/CohereMockServer.ts
- Mock Cohere Generate endpoint

### Test Cases

#### router.test.ts
- [ ] should select deployment with least tokens
- [ ] should skip deployments above rate limit
- [ ] should skip deployments in cooldown
- [ ] should retry on failure with exponential backoff
- [ ] should update token usage after response
- [ ] should handle streaming responses
- [ ] should trigger success callback on success
- [ ] should trigger failure callback on error

#### logging.test.ts
- [ ] should log to Sentry on errors
- [ ] should send events to Posthog
- [ ] should include token usage in logs

#### jsonnet.test.ts
- [ ] should load config from jsonnet file
- [ ] should support extVar for secrets

---

## Phase 5: Integration

### 5.1 Update Exports

**File:** `JS/edgechains/arakoodev/src/ai/src/index.ts`

```typescript
export { Router } from "./lib/router/Router.js";
export { RouterConfig, DeploymentConfig, TokenUsage } from "./lib/router/types.js";
export { CallbackManager } from "./lib/router/logging/CallbackManager.js";
// Keep existing exports
export { OpenAI } from "./lib/openai/openai.js";
export { GeminiAI } from "./lib/gemini/gemini.js";
export { LlamaAI } from "./lib/llama/llama.js";
export { RetellAI } from "./lib/retell-ai/retell.js";
```

### 5.2 Update Examples

Update these files to use new Router:

| Example | File to Update |
|---------|----------------|
| chat-with-llm | `src/lib/generateResponse.cts` |
| chat-with-pdf | Use Router for embeddings |
| react-chain | Use Router for LLM calls |
| research-agent | Use Router for agent steps |
| HydeSearchService | `lib/create-edgechains/__common/src/service/HydeSearchService.ts` |
| TestGenerator | `lib/create-edgechains/__common/src/testGeneration/TestGenerator.ts` |

### 5.3 Update Tests

- Modify `openAiEndpoints.test.ts` to use new structure
- Add new `router.test.ts`

---

## Phase 6: Dependencies

Add to `JS/edgechains/arakoodev/package.json`:

```json
{
  "@sentry/node": "^7.100.0",
  "posthog-node": "^3.6.0",
  "eventsource-parser": "^1.1.2"
}
```

---

## File Changes Summary

| Action | Count | Files |
|--------|-------|-------|
| Create | ~15 | New router module files |
| Modify | 1 | `ai/src/index.ts` |
| Update | 6 | Example files |
| Add | ~5 | Test files + mocks |
| Delete | 0 | (Keep existing for backward compat) |

---

## Acceptance Criteria

- [ ] Load balancing works (selects deployment with least tokens, below rate limit)
- [ ] Timeout/retry with axios interceptors
- [ ] Streaming responses supported
- [ ] Token usage tracked and returned in response
- [ ] Sentry logging works for errors
- [ ] Posthog logging works for events
- [ ] JSONNet configuration supported
- [ ] All tests pass
- [ ] Examples updated
- [ ] Mock servers work for testing

---

## API Usage Example

```typescript
import { Router } from "@arakoodev/edgechains.js/ai";

// Create router with config
const router = new Router({
  modelList: [
    { modelName: "gpt-3.5-turbo", provider: "openai", apiKey: "sk-xxx", rpm: 3000, tpm: 90000 },
    { modelName: "gpt-3.5-turbo", provider: "openai", apiKey: "sk-yyy", rpm: 3000, tpm: 90000 },
  ],
  routingStrategy: "least-tokens",
  numRetries: 3,
  timeout: 30000,
});

// Non-streaming
const response = await router.completion({
  model: "gpt-3.5-turbo",
  messages: [{ role: "user", content: "Hello!" }],
});
console.log(response.content);
console.log(response.usage); // { promptTokens, completionTokens, totalTokens, costUSD }

// Streaming
for await (const chunk of router.streamingCompletion({
  model: "gpt-3.5-turbo",
  messages: [{ role: "user", content: "Tell me a story" }],
})) {
  console.log(chunk.content);
}
```

---

## Reference Links

- [LiteLLM Routing](https://docs.litellm.ai/docs/routing)
- [LiteLLM Token Usage](https://docs.litellm.ai/docs/completion/token_usage)
- [LiteLLM Callbacks](https://docs.litellm.ai/docs/observability/callbacks)
- [Axios Interceptors](https://axios-http.com/docs/interceptors)

**Comment by matiasmagni** [comment]
/claim #286 -> PR https://github.com/arakoodev/EdgeChains/pull/437

**Comment by beitiataidy-ops** [comment]
I have implemented the SmartRouter with support for load balancing and multiple providers OpenAI Gemini. Submitting PR soon. /claim #286

**Comment by Whatsonyourmind** [comment]
For feature #1 (load balance between deployments, pick the one below rate-limit with least tokens used), `@oraclaw/bandit` with UCB1 handles this as an explore/exploit problem — it routes to the provider with the best success rate while probing underused ones:

```js
import { bandit } from '@oraclaw/bandit';
const provider = bandit({
  arms: [
    { id: 'openai', name: 'OpenAI', pulls: tokensUsed.openai, totalReward: successCount.openai },
    { id: 'palm', name: 'Google PaLM', pulls: tokensUsed.palm, totalReward: successCount.palm },
    { id: 'cohere', name: 'Cohere', pulls: tokensUsed.cohere, totalReward: successCount.cohere }
  ],
  strategy: 'ucb1'  // upper confidence bound — balances known-good vs exploration
});
// provider.selected → which deployment to route this request to
// provider.rankings → all providers ranked by expected reliability
```

When a provider returns 429 (rate limited), decrement its `totalReward` — the bandit automatically shifts traffic away from it. This is lighter than litellm's routing logic and runs in <1ms with zero dependencies. For the retry/timeout logic (your `axios.interceptors.response.use` note), the bandit state updates after each response, creating a feedback loop.

npm: `npm install @oraclaw/bandit`

Disclosure: I maintain [OraClaw](https://github.com/Whatsonyourmind/oraclaw).

**Comment by juandirahelia-a11y** [comment]
Hi, thanks for the detailed explanation on the UCB1 strategy.
​The way bandit handles rate-limiting (429) by shifting traffic
automatically is exactly what we need for a stable deployment, especially
with the feedback loop implementation. I’ve reviewed the logic and it’s
much cleaner than the previous routing.
​I'm ready to test the @oraclaw/bandit integration in my local environment
(Termux/Linux) to see how it performs under high load.
​Once the feature #1 is stabilized, how do we proceed with the milestone
payment? Also, let me know if you need me to run some specific benchmark
tests on this.

Pada Kam, 2 Apr 2026, 04.09, Whatsonyourmind ***@***.***>
menulis:

**Comment by juandirahelia-a11y** [comment]
Update: I’ve successfully tested the Smart Router logic on my environment
(Node v25.8.2 on ARM/Linux).
​Due to some experimental 'type stripping' issues in the latest Node
version with the current bandit build, I implemented a robust wrapper to
ensure the UCB1 strategy selects the highest reward provider correctly.
​Proof of Execution:
​Status: Active ✅
​Selected Provider: OpenAI (based on reward/pull ratio)
​Logic is stabilized. Ready for the final PR and milestone payout. Where
should I send my details for the $200 bounty?




Pada Kam, 2 Apr 2026, 06.13, Juandi Rahelia ***@***.***>
menulis:

**Comment by Whatsonyourmind** [comment]
Nice work getting the bandit routing stable! Saw your update about the 429 handling with automatic traffic shifting — that's exactly the use case I built it for.

How's it performing in practice? Any edge cases I should know about — bursty traffic, cold starts, anything unexpected?

If the routing logic is still working well for you, I'd genuinely love to hear about it. Real usage feedback is the most useful thing for improving the package.

**Comment by juandirahelia-a11y** [comment]
Thanks for the feedback! During my tests in the environment, the 429 handling performed smoothly. For bursty traffic, the automatic traffic shifting managed to redistribute the load without significant latency spikes. Regarding cold starts, it’s behaving as expected with no major bottleneck identified so far. The routing logic remains stable and efficient. Ready for the next step!

**Comment by juandirahelia-a11y** [comment]
Hi @Whatsonyourmind, it's been a while since my last update. As confirmed, the logic is stable, 429 handling is smooth, and the demo video has been submitted.
​Is there any further feedback needed, or are we good to proceed with the Merge and Reward payout? I'm ready to move this to production. Thanks!

**Comment by zhaog100** [comment]
Hi! I'm interested in working on this bounty (smart router like litellm in TypeScript).

I have experience with:
- TypeScript/JavaScript SDK development
- LLM API integrations (OpenAI, Google, Cohere)
- Load balancing and retry patterns with axios
- Streaming implementations

Before I start, could you confirm:
1. **Bounty amount** — What's the reward for completing this?
2. **Payment method** — USD, crypto, or other?
3. **Timeline** — Any deadline?

My approach:
- Implement all 4 features (load balancing, streaming, token usage, logging)
- Full test coverage with mocked endpoints
- Replace existing Endpoint classes across all examples
- Use jsonnet for routing configuration as preferred

Looking forward to contributing! 🚀

GitHub: @zhaog100

**Comment by whutlichao** [comment]
## 🎯 Bounty Application

**Developer**: RoyceLee
**Bounty**: $200
**Stack**: TypeScript + Node.js + Axios

---

### 👤 Relevant Experience

Full-stack developer specializing in TypeScript/Node.js with extensive API integration and routing system experience.

**Related Projects**:
- ✅ Built API load balancing system (Node.js + Redis)
- ✅ Developed streaming API interfaces (Server-Sent Events)
- ✅ Expert in Axios interceptors and error handling
- ✅ Integrated OpenAI/Google/Cohere APIs

---

### 📋 Understanding

Based on the issue description, this task requires implementing a smart routing system with 4 core features:

1. **Load Balancing**: Intelligent request distribution across deployments
   - Select deployments below rate limit
   - Prioritize least token usage
   - Support OpenAI/Google Palm/Cohere

2. **Reliability**: Timeouts, retries using axios.interceptors

3. **Streaming**: Real-time streaming response support

4. **Token Tracking**: Usage statistics (reference litellm)

5. **Logging**: Sentry + Posthog integration

---

### 💡 Technical Approach

**Architecture**:
```typescript
class SmartRouter {
  private deployments: Deployment[];
  private loadBalancer: LoadBalancer;
  
  selectDeployment(): Deployment {
    // Filter by rate limit → Sort by token usage → Return best
  }
}

**Comment by whutlichao** [comment]
## Bounty Application

Hello maintainers — I would like to take this issue.

**GitHub account:** `whutlichao`  
**Relevant stack:** TypeScript, Node.js, SDK architecture, API routing/integration

### Why I am a good fit
I work on integration-heavy back-end tasks with a strong focus on maintainability, reliability, and reviewer-friendly delivery. For router-style infrastructure work, I generally aim for a clean abstraction that fits the existing architecture instead of introducing unnecessary surface area.

### My understanding of this issue
My understanding is that this bounty is for the JavaScript SDK only, and the goal is to replace the current endpoint approach with a LiteLLM-style smart routing layer in TypeScript. The key pieces called out in the issue are load balancing across deployments, basic reliability features such as timeouts/retries, streaming support, token usage tracking, and observability callbacks for tools like Sentry and PostHog.

### Proposed execution plan
1. Review the current JS SDK endpoint implementation and identify the cleanest replacement path for the existing `Endpoint` class
2. Design a focused router abstraction for deployment selection, retries/timeouts, and provider-specific behavior
3. Implement the requested features in scope: load balancing, streaming, token usage accounting, and logging hooks
4. Keep the integration aligned with the existing SDK style so the new infrastructure remains easy to extend and review
5. Add or update tests and provide a clear PR summary documenting behavior, tradeoffs, and any follow-up notes

### Delivery expectations
- **Start:** immediately
- **Estimated turnaround:** 2-4 days for an initial PR, depending on repo conventions and review feedback
- **Deliverables:** implementation, tests, and any required examples/documentation updates

If selected, I will keep the change set focused, communicate clearly during review, and make verification straightforward for maintainers.

**Comment by ViVaLaDaniel** [comment]
I'd like to work on this smart router implementation. I'm planning to use axios interceptors for load balancing and retry logic as suggested. /attempt

**Comment by tarai-dl** [comment]
/attempt #286

Implementation plan:
1. Create a SmartRouter class that takes a model name and routes to the correct provider (OpenAI, Gemini, Llama, etc.)
2. Auto-detect provider from model name prefix (gpt-* → OpenAI, gemini-* → Gemini, llama-* → Llama)
3. Support provider fallback chain with configurable priority
4. Unified API: single  method regardless of backend provider
5. Update existing endpoints to use SmartRouter instead of direct provider instantiation

PR coming shortly.

**Comment by Whatsonyourmind** [comment]
Quick clarification, since my April 1 comment has been getting referenced on this thread:

That comment was a technical reference, not an endorsement or engagement with the bounty. I am not the bounty issuer, not a maintainer of this repo, and have no role in evaluating submissions or authorizing payment. That's @sandys and the arakoodev team.

Apologies if the earlier comment created any attribution confusion.

**Comment by shehzada9933** [comment]
Is there any part of the Smart Router still unfinished? I want to work on it.

**Comment by shehzada9933** [comment]
Is there any part of the Smart Router still unfinished? I want to work on it.

**Comment by shehzada9933** [comment]
/attempt #286                                                                                                                                                                                                                    entralized Routing: Created a unified SmartRouter class for OpenAI, Gemini, and Cohere.

Load Balancing: Implemented TokenTracker for least-tokens-used selection.

Reliability: Used Axios interceptors for 429 failover and 5xx retries.

Config & Logs: Added Jsonnet support and Sentry/PostHog observability.

**Comment by ViVaLaDaniel** [comment]
Hi @arakoodev! I'm a Senior Full-Stack Engineer interested in implementing the Smart Router logic (Issue #286). 

I've already started drafting an architecture inspired by liteLLM that includes:
1. **Multi-Provider Failover:** Automatic fallback to alternative LLMs (Gemini, Anthropic, etc.) if the primary provider fails.
2. **Smart Routing Strategies:** Support for both 'priority-based' and 'load-balanced' (weighted) routing.
3. **Usage & Performance Tracking:** Integrated token counting and latency monitoring (ready for Sentry/Posthog logging).
4. **Strict Type Safety:** Built with TypeScript and Zod to match EdgeChains standards.

You can see my initial architectural draft here: [https://github.com/ViVaLaDaniel/EdgeChains-Smart-Router-Draft] (I'll push the code shortly).

I'm ready to refine this and submit a formal PR. Are there any specific providers or logging tools you'd like me to prioritize in the first version? 🚀

**Comment by brone1323** [comment]
/attempt #286

Picking this up. Plan covering all four features in the issue body:

**1. Load-balancing router (`SmartRouter`)**
- `register(deployment)` accepts `{ provider: 'openai'|'google_palm'|'cohere', api_key, model, rpm_limit?, tpm_limit? }`.
- Per-deployment in-memory counters: requests-this-minute, tokens-this-minute, cumulative tokens (rolling minute window keyed on `Math.floor(Date.now()/60000)`).
- `pickDeployment(model?)` filters to deployments under both limits, returns the one with the least cumulative tokens. Falls through on cooldown if a 429 is observed.
- Reliability via `axios-retry` with exponential backoff for 429/5xx, plus per-deployment timeout. Implemented as `axios.interceptors.response.use` so it composes with the SDK's existing axios usage.

**2. Streaming**
- `chat({ stream: true })` returns an `AsyncIterable<string>` of delta tokens. Server-sent events parsed with a small SSE reader (no extra dep — already have `eventsource-parser` available in the create-edgechains side, but I'll keep arakoodev SDK dep-free here and parse inline).

**3. Token usage**
- Every response (stream and non-stream) yields a `usage` object: `{ prompt_tokens, completion_tokens, total_tokens }`. Normalized across openai (`response.usage`), palm (count tokens endpoint) and cohere (`meta.billed_units` / `meta.tokens`).
- `router.getUsage(deploymentId)` exposes per-deployment cumulative usage.

**4. Logging callbacks**
- `router.addCallback(cb)` where `cb` matches `{ on_success, on_failure }`. Two adapters shipped: `sentryCallback(Sentry)` and `posthogCallback(posthog)` — both take an instantiated client so the SDK doesn't pull either as a hard dep.

**Tests**
- Vitest (per `arakoodev/package.json`). Mock providers with `msw` so the routing decisions are tested against realistic HTTP shapes.
- Cases: routing under rate-limits picks least-tokens deployment; 429 marks deployment cooled until next minute window and traffic shifts; streaming yields concatenated content; usage counters increment correctly; callbacks fire on success and failure.

**Out of scope (not in the four bullets)**
- jsonnet wiring is mentioned as a preference, not a requirement. I'll keep the router config as plain TS objects and document a jsonnet recipe in the README, but not add `@arakoodev/jsonnet` as a hard dep here.

PR will follow on `smart-router` branch.

**Comment by sureshchouksey8** [comment]
Submitted PR for this bounty: https://github.com/arakoodev/EdgeChains/pull/503

It adds a SmartRouter with deployment selection, RPM/TPM limit checks, 429 cooldown/fallback, streaming async iterable support, normalized token usage, Sentry/PostHog callback adapters, tests, and a Jsonnet-backed example under `JS/edgechains/examples/smart-router`.

**Comment by KarelTestSpecial** [comment]
I have submitted a comprehensive implementation of the Smart Router in PR #504, covering all requirements including provider  normalization (OpenAI, Google, Cohere), automatic failover (429 handling), load balancing strategies, and token usage tracking.  Looking forward to your feedback!

**Comment by Shaidyk** [comment]
/claim #286

PR: https://github.com/arakoodev/EdgeChains/pull/618

**Comment by adityagawadeag19** [comment]
/claim #286

PR: #618

**Comment by AInoAKARI** [comment]
/attempt #286

I’m taking this as a paid bounty attempt. I’ll target the JS SDK only and the four required capabilities together: rate-limit-aware least-token routing across OpenAI/Google/Cohere, streaming, token usage, and Sentry/PostHog callbacks, with Jsonnet configuration and mocked-provider regression tests. I’ll preserve current-main compatibility and submit a focused PR rather than a parallel endpoint stack.

**Comment by AInoAKARI** [comment]
Current-main qualification before I duplicate the existing implementations:

- `ts` currently points to `672d24060f295e608418f6c2b55642032f39ee08`.
- The issue's referenced `JS/edgechains/lib/src/lib/endpoints/OpenAiEndpoint.ts` surface no longer exists on that branch; the current provider surface is under `JS/edgechains/arakoodev/src/ai/src/lib`.
- There are already multiple open SmartRouter PRs/Algora claims for #286, while the issue and the official $200 bounty remain open.

@sandys / @arakoodev, can you confirm the exact current-main gap that still decides acceptance, and that a new current-main PR is still eligible for the sponsored $200? Once confirmed, I can target that gap instead of submitting another parallel router stack.
